spring:
  profiles:
    active: discovery-client
  application:
    name: user-service
  #datasource configurations
  datasource:
    url: "jdbc:mysql://host.docker.internal:3306/mobile_tracker_user_development"
    driver-class-name: com.mysql.jdbc.Driver
    username: "{cipher}AQAGFxC/Nf/170JdpnAXjUVaMOIGnfbZ+SyG4DU1VjgKcNpnkP9AEoqMcbYaZ+7c/+tF61oDYwj6rdTnpvdKhWN9BJD4Yv9dBapyhCKWM4s5mfHJTSRCc5WqfkMihFggnGcGfqa+F7PDW7t1qSjVdXNJ9AbanQc95DsryscRSAJtjeBK6TZ9IVHqtsesTD76ROSJDuGJmVSBYjdyh2ReyX8UKa8VYzYki9DjFj6/OMcxtqHpyrniRLzWR0lLXWGjtjIvsLlj2H/mILAj+fkiEUcaOl4aX4n56/2TqcvdtvOJpmp9HBVDSfhvP1MKfganKbyK8xrrsHP19kHyu5OHqpaB7s8WzA2BmghiJaBLfh4o+kV43E0A5osE3sBZDtiv/Os="
    password: "{cipher}AQCnwi8OrFYhG5skkWJak/AW5f9C6im6DlLWa6QQP0GxMkWDnZAZf8PwoDuGxY/jfkFMOYXE+e04dtNUVi9sjvUHIRJxH7ztBQYPe/NNBJGHrNntT8G/3mPeVmNGCGZ587un2HGvUAownOvwDvKmAC+JVb7q87nrzVRmyuvpbqXuIuvpIMDHqsi0oIbFSXQmlAOKcd4H+pa+SgoGQ1zFAVGmocoysQcVYldh3FJZqiE2vAmX5Rwp6X94wk4UednkelFvj3Z9qJ6fq9HXb26fvl3ChMa46/Se51ddN50C19jN83E/S/YZHL6liBFy6n8e4dGehL4ALA4OfE6XM/kKJDtVzryWk8GamK0DkdMoPTQUtAwWtXSfoBzFANDDX6qZ7rqVBZ6yHcE1/JH9ohci142e"
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  #freemarker configurations
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  #mail configurations
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    #other smtp properties
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        transport.protocol: smtp
        debug: false
    
#user microservice security configurations
user:
  security:
    jwt:
      login-url: /login
      logout-url: /logout
      generate-refresh-token-url: /refresh-token
      expiration-refresh-token: 1209600000
      secret-refresh-token: "{cipher}AQC2UOL7X4V8pcpmmxwNKzdzzTP4rCiQdIlogMlsay+xNchU24Txxtv0LGyP2W01BpWHGj66oNTyGM7HG8n+RFXT/dlstVzVYKyWaUtvvT+f6h/+S5eHQzOMzsDZ5XiVulXHNJSy8V6GVJ1wQYe6PpqPP1BdGrAqPIeAMVls90suirTRRC8v3C0jBwuvbuoRtkzpcFnAMohvZsstNMNMs/K9C/GvNQcvio7WTU8MCJOubmMM56rCNjZemWTbje2Jd4CIuFfKQ+eZ1Jltbd98mNzcDGKiKWz9l+BGd2mXz5uV5vkdpzoEiWg9tGBsa7UYoPMNY9ZmtF2NH3+J3tJg+AbohJ/jO7O7uWieJaT8zWHGfKFmuIQW1ZQ3k6ylAyVuJKEWvsQ2ITX1IXsr2cBBmyo1qoEp2zHyB3AUqdwDPW97/cltjiBgpCL27+lu1IQpY5ehLuzCnVp8HA5SWWuKw276hvOyKAIStjYHHxRz67p74geTafEPILR+7q25bcV1WQ3If8Tr5bdiovBlR8lcxXNKGu7lo/o4xIWKFaJeaituLUwponQ2N4p9ZSsdS7e1nc5KCv4GH3SfRwBfi+/0LxrG"