#configs for user jwt security
user:
  security:
    jwt:
      header: 
        - Authorization
        prefix: Bearer
      expiration: 1800000
      secret: ZjsanferfndSFDSc453423dsCASCASdascdmc323432dscs0-qwddasxaskcnw