#Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
